### ISSUE TITLE
Cache data not captured in AX when a127 proxy is deployed on Edge

### ISSUE THREAD

**Issue by WWitman** [apigee-127/volos#73] opened 2015-03-10 23:28 UTC
See the following Community thread for details:

https://community.apigee.com/questions/1797/the-cache-performance-analytics-says-no-data-to-sh.html#answer-1885

**Comment by theganyo** [comment] 2015-03-11 17:38
This will probably need to be investigated on the Edge side.

**Comment by theganyo** [comment] 2015-03-11 20:01
Per @jwest-apigee:

For 127 on edge a127 is being treated as a target system. If a target system returns something from its cache Edge will not know. 

If we want to change how AX records are being reported for a127 on edge then we have to do something in both edge and a127 so edge knows that a127 returned from its cache.

**Comment by emcpadden** [comment] 2015-03-11 21:08
Oh .. this makes sense why it didn't show up in the Cache Performance page in analytics.  It would really be nice to have though ... would really help to tune how the cache should work and also just give general insight into caching which could help when trying to diagnose caching problems.

**Comment by theganyo** [comment] 2015-10-05 23:33
Closing as duplicate of #64

**Closed** 2015-10-05 23:33 UTC
